# .github/workflows/build.yml
name: Build check-debian-sources

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出源码
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. 安装编译依赖
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc libcurl4-openssl-dev

    # 3. 编译
    - name: Build binary
      run: |
        gcc -O2 -o liveorno liveorno.c -lcurl
        chmod +x liveorno

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: check-debian-sources-${{ runner.os }}
        path: check-debian-sources
